// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_ReverseEngineer_and_CodeFirst
{
    public partial class Inspections
    {
        public int Id { get; set; }
        public string Status { get; set; }
        public string Comments { get; set; }
        public int InspectionTypeId { get; set; }

        public virtual InspectionTypes InspectionType { get; set; }
    }
}