// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace EF_ReverseEngineer_and_CodeFirst
{
    public partial class Statuses
    {
        public int Id { get; set; }
        public string StatusOption { get; set; }
    }
}